service: API
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true